### ISSUE TITLE
forced to reply when adding image

### ISSUE THREAD

**Issue by fr4ctical3** [ryandolan123/TweetDeck-Enhancer#10]
If you start replying to someone's tweet and then cancel the reply, if you later drag and drop an image into the new tweet column, the tweet will become a reply to the same tweet. the only way to stop this from happening is to refresh tweetdeck.

please see attached .gif
![tde_bug 2](https://cloud.githubusercontent.com/assets/10366519/5593186/183f230c-91b1-11e4-8b4b-6fe632705bba.gif)

**Comment by ryandolan123** [comment]
This has been resolved by fixing the cancel reply button in 4.2. The reply reappearing sounds like a problem within tweetdeck and not tweetdeck enhancer.
