### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by Apph3x** [ryandolan123/TweetDeck-Enhancer#11]
See the pic attached - When lot's of people are tagged this sometimes happens 
![screen shot 2015-01-03 at 18 56 54](https://cloud.githubusercontent.com/assets/6704113/5603389/2cee8038-937b-11e4-8d1c-b83c1d142155.png)

**Comment by ryandolan123** [comment]
I've been testing this in multiple scenarios with long lists of people and found this unreproducible.

**Comment by Apph3x** [comment]
Ok but I reloaded the page and reproduced this

**Comment by ryandolan123** [comment]
Perhaps I accidentally fixed the problem as I am running a 4.2 prerelease version. I'll tag it as fixed.

**Comment by Apph3x** [comment]
Maybe you did fix it.....
