### ISSUE TITLE
TDE 5 -- Bug

### ISSUE THREAD

**Issue by Apph3x** [ryandolan123/TweetDeck-Enhancer#17]
Lovely menu bar bug in TDE 5 :P 
![tde 5](https://cloud.githubusercontent.com/assets/6704113/6005290/27c369aa-ab01-11e4-8386-c8e2c938e0c2.png)

**Comment by ryandolan123** [comment]
What about it? If it's the fact that it has my header and name, that's just a placeholder.

**Comment by Apph3x** [comment]
Wait so its hard coded

-----Original Message-----

**Comment by ryandolan123** [comment]
Yes
