### ISSUE TITLE
Add ability to insert emoji

### ISSUE THREAD

**Issue by vipbird12** [ryandolan123/TweetDeck-Enhancer#21]
I switched from [Better TweetDeck](https://github.com/eramdam/BetterTweetDeck) to TweetDeck Enhancer about a week ago, however one thing I miss is the ability to insert emoji when composing a tweet, as shown in this screenshot from Better TweetDeck's README.md:  
![image](https://cloud.githubusercontent.com/assets/1476338/6244255/ac1043ec-b748-11e4-8530-ab0d5421472e.png)  
Here is a quick mock-up of what this button might look like in TDE:  
![image](https://cloud.githubusercontent.com/assets/1476338/6244429/469d50d8-b74b-11e4-952f-5e2d6b4044e0.png)
I understand that this is certainly not a critical feature to add, but it might not be overly complicated to implement. Better TweetDeck is released under the MIT License, so redistributing the code would not be a problem. I am not very experienced with programming myself, however I might have a look and see what I could do. :smile:

**Comment by Apph3x** [comment]
Buy a mac. Press Contrl, CMD and space.

**Comment by ryandolan123** [comment]
This ^

Also Better TweetDeck and Enhancer are compatible.

**Comment by vipbird12** [comment]
I do not own a Mac, but I'm sure the shortcut will come in handy one day. I also didn't know that BTD and TDE were compatible. I've tried it and it works perfectly. Thanks for the tip!
